<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bol.Tec.11(2)|Lab.EPOMAR(UdeC)|CRUSTASUR">

<title>Indicadores biológico-pesqueros de langostino colorado, langostino amarillo y camarón nailon, (abril 2026)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="BolTec1102_files/libs/clipboard/clipboard.min.js"></script>
<script src="BolTec1102_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="BolTec1102_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="BolTec1102_files/libs/quarto-html/popper.min.js"></script>
<script src="BolTec1102_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BolTec1102_files/libs/quarto-html/anchor.min.js"></script>
<link href="BolTec1102_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BolTec1102_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BolTec1102_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BolTec1102_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BolTec1102_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">1 Resumen</a></li>
  <li><a href="#aspectos-pesqueros" id="toc-aspectos-pesqueros" class="nav-link" data-scroll-target="#aspectos-pesqueros">2 Aspectos Pesqueros</a>
  <ul class="collapse">
  <li><a href="#actividad-pesquera" id="toc-actividad-pesquera" class="nav-link" data-scroll-target="#actividad-pesquera">2.1 Actividad pesquera</a></li>
  <li><a href="#captura-esfuerzo-y-rendimientos-de-pesca" id="toc-captura-esfuerzo-y-rendimientos-de-pesca" class="nav-link" data-scroll-target="#captura-esfuerzo-y-rendimientos-de-pesca">2.2 Captura, esfuerzo y rendimientos de pesca</a></li>
  </ul></li>
  <li><a href="#aspectos-biológicos" id="toc-aspectos-biológicos" class="nav-link" data-scroll-target="#aspectos-biológicos">3 Aspectos biológicos</a>
  <ul class="collapse">
  <li><a href="#proporción-sexual-y-talla-promedio" id="toc-proporción-sexual-y-talla-promedio" class="nav-link" data-scroll-target="#proporción-sexual-y-talla-promedio">3.1 Proporción sexual y talla promedio</a></li>
  <li><a href="#aspectos-reproductivos" id="toc-aspectos-reproductivos" class="nav-link" data-scroll-target="#aspectos-reproductivos">3.2 Aspectos reproductivos</a></li>
  <li><a href="#composición-de-tallas" id="toc-composición-de-tallas" class="nav-link" data-scroll-target="#composición-de-tallas">3.3. Composición de tallas</a></li>
  <li><a href="#fauna-acompañante" id="toc-fauna-acompañante" class="nav-link" data-scroll-target="#fauna-acompañante">3.4 Fauna acompañante</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Indicadores biológico-pesqueros de langostino colorado, langostino amarillo y camarón nailon, (abril 2026)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bol.Tec.11(2)|Lab.EPOMAR(UdeC)|CRUSTASUR </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div style="page-break-after: always;"></div>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">1 Resumen</h2>
<p>Durante abril de 2026, la actividad pesquera de la flota de CrustaSur se desarrolló entre las regiones del Biobío y del Libertador General Bernardo O’Higgins, abarcando principalmente los caladeros de San Vicente, Itata, Chanco, Carranza, Iloca y Pichilemu. La operación estuvo dominada por lances con captura exclusiva de langostino colorado y por lances mixtos de langostino colorado y langostino amarillo, mientras que el camarón nailon se concentró en caladeros específicos, principalmente Chanco e Itata. En términos operacionales, el langostino colorado registró la mayor captura mensual, con 384 toneladas y un rendimiento promedio de 1281 kg/ha., seguido por langostino amarillo, con 48 toneladas y 352 kg/ha., y camarón nailon, con 46 toneladas y 693 kg/ha.</p>
<p>Desde el punto de vista biológico, el langostino colorado y el camarón nailon presentaron una proporción sexual favorable a las hembras, mientras que en langostino amarillo predominaron los machos. Las tallas medias de langostino colorado se mantuvieron en torno a 36–38 mm LC, con valores relativamente similares entre sexos. En langostino amarillo se observó un repunte de las tallas respecto de marzo, especialmente en machos, que alcanzaron una talla media de 40,0 mm LC, mientras que las hembras registraron 31,7 mm LC. En camarón nailon, las hembras presentaron una talla media cercana a 30 mm LC, superior a la registrada en machos.</p>
<p>En relación con los aspectos reproductivos, el 20 % de las hembras de langostino colorado se encontró en condición ovígera, proporción similar a la registrada durante el año anterior. En langostino amarillo no se observó presencia de hembras ovígeras, manteniéndose la tendencia descrita desde 2017. En camarón nailon, el 27 % de las hembras correspondió a ejemplares maduros o portadores, mientras que predominó la fracción inmadura.</p>
<p>La composición de tallas mostró diferencias entre recursos y zonas de pesca. En langostino colorado, las tallas modales más pequeñas se registraron en San Vicente, mientras que las mayores se observaron en Pichilemu. En langostino amarillo, las tallas fueron relativamente similares entre San Vicente e Itata, manteniendo el repunte observado durante abril. En camarón nailon, las mayores tallas se observaron en Chanco, especialmente en hembras. Finalmente, la fauna acompañante estuvo representada principalmente por pejerrata, merluza, lenguado, jaiba paco y jaiba limón, con baja participación relativa respecto de las capturas objetivo.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="aspectos-pesqueros" class="level1">
<h1>2 Aspectos Pesqueros</h1>
<section id="actividad-pesquera" class="level2">
<h2 class="anchored" data-anchor-id="actividad-pesquera">2.1 Actividad pesquera</h2>
<p>La distribución espacial de los lances muestra una operación concentrada en sectores costeros discretos, asociados a caladeros históricamente relevantes para la pesquería de crustáceos demersales. Durante abril de 2026, la actividad se desarrolló desde la región del Biobío hasta la región del Libertador General Bernardo O’Higgins, destacando los caladeros de Pichilemu, Iloca, Carranza, Chanco e Itata (Fig. 1).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/lances_abril.jpeg" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Distribución espacial del total de lances de pesca realizados durante abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="captura-esfuerzo-y-rendimientos-de-pesca" class="level2">
<h2 class="anchored" data-anchor-id="captura-esfuerzo-y-rendimientos-de-pesca">2.2 Captura, esfuerzo y rendimientos de pesca</h2>
<p>Durante abril de 2026, la actividad pesquera se concentró principalmente en lances con captura exclusiva de langostino colorado, los que representaron el 41 % del total, y en lances con captura mixta de langostino colorado y langostino amarillo, que representaron el 37 %. En segundo lugar, el 13 % de los lances estuvo orientado exclusivamente a camarón nailon. El porcentaje restante correspondió a lances con presencia simultánea de los tres recursos u otras combinaciones de menor frecuencia (Fig. 2). En cuanto a las capturas de estas especies por caladero, en la mayoría predominó el langostino colorado. El langostino amarillo presentó mayor participación relativa en Iloca, mientras que en Chanco la captura estuvo compuesta exclusivamente por camarón nailon.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/lances_especies-abril.jpeg" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Distribución espacial de los lances de pesca orientados a langostino colorado, langostino amarillo y camarón nailon durante abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<p>Respecto de marzo, los tres recursos presentaron una disminución en el rendimiento promedio, particularmente langostino colorado y langostino amarillo. En langostino colorado, las capturas alcanzaron 384 toneladas, con un promedio de 2372 kg por lance, un esfuerzo total de 230 horas de arrastre y un rendimiento de pesca de 1281 kg/ha (Tabla 1). Para langostino amarillo, se registraron 86 lances, una captura total de 48 toneladas y un rendimiento promedio de 352 kg/ha. En tanto, el camarón nailon estuvo presente en 37 lances, acumulando 46 toneladas de captura total.</p>
<div style="page-break-after: always;"></div>
<section id="tabla-1.-indicadores-operacionales-de-la-pesquería-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-año-2026." class="level5">
<h5 class="anchored" data-anchor-id="tabla-1.-indicadores-operacionales-de-la-pesquería-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-año-2026."><em>Tabla 1. Indicadores operacionales de la pesquería de langostino colorado, langostino amarillo y camarón nailon, año 2026.</em></h5>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Recurso</strong></th>
<th><strong>Mes</strong></th>
<th><strong>N° de lances(n)</strong></th>
<th><strong>Cap. (kg)</strong></th>
<th><strong>Cap.lances (kg/n)</strong></th>
<th><strong>h arrast.(ha)</strong></th>
<th><strong>Rend. (kg/ha)</strong></th>
<th><strong>Prof.de fondo(m)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>marzo</td>
<td>137</td>
<td>351754</td>
<td>2567</td>
<td>121</td>
<td>2907</td>
<td>249</td>
</tr>
<tr class="even">
<td></td>
<td>abril</td>
<td>162</td>
<td>384280</td>
<td>2372</td>
<td>230</td>
<td>1281</td>
<td>224</td>
</tr>
<tr class="odd">
<td><strong>L.amarillo</strong></td>
<td>marzo</td>
<td>83</td>
<td>42789</td>
<td>515</td>
<td>49</td>
<td>877</td>
<td>264</td>
</tr>
<tr class="even">
<td></td>
<td>abril</td>
<td>86</td>
<td>48702</td>
<td>566</td>
<td>138</td>
<td>352</td>
<td>238</td>
</tr>
<tr class="odd">
<td><strong>Camarón</strong></td>
<td>marzo</td>
<td>57</td>
<td>98820</td>
<td>1733</td>
<td>87</td>
<td>1138</td>
<td>324</td>
</tr>
<tr class="even">
<td></td>
<td>abril</td>
<td>37</td>
<td>46825</td>
<td>1265</td>
<td>67</td>
<td>693</td>
<td>283</td>
</tr>
</tbody>
</table>
<p>El rendimiento de pesca del langostino colorado varió entre 150 y 4224 kg/ha, con una moda de 1318 kg/ha. Por su parte, el esfuerzo por lance fluctuó entre 20 y 238 minutos, concentrándose principalmente en torno a 1 hora 50 minutos (Fig. 3). En el caso del langostino amarillo, el rendimiento osciló entre 9 y 1416 kg/ha, mientras que el esfuerzo se concentró mayoritariamente en lances de 1 hora 30 minutos. Por su parte, el camarón nailon presentó un rendimiento medio de 693 kg/ha, con esfuerzos cercanos a 2 horas.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/esf_rend_abril.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de frecuencia del esfuerzo de pesca (en horas de arrastre, A) y del rendimiento (en kg/ha, B), para langostino colorado, langostino amarillo y camarón nailon durante abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<p>Durante abril, los mayores rendimientos de langostino colorado se registraron en los caladeros de Iloca, Carranza e Itata, con valores medios del orden de 1300 a 1500 kg/ha (Fig. 4,5). La captura de langostino amarillo mostró su mejor desempeño en Iloca y Constitución, con rendimientos de 1000 kg/ha (Fig. 4,5). En tanto, el camarón nailon presentó sus valores más altos en el caladero de Itata, donde los rendimientos fluctuaron entre 2000 y 4000 kg/ha (Fig. 4,5).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/cpue_espec_abril.jpeg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Rendimiento de pesca (captura por hora de arrastre) de langostino colorado (A), langostino amarillo (B) y camarón nailon (C), en abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/redim_caladero_abril.jpg" class="img-fluid figure-img" style="width:110.0%"></p>
<figcaption>Distribución del rendimiento de pesca (kg/ha) de langostino colorado, langostino amarillo y camarón nailon en abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="aspectos-biológicos" class="level1">
<h1>3 Aspectos biológicos</h1>
<p>Los indicadores biológicos considerados incluyeron la talla promedio por sexo, proporción sexual, estructura de tallas, condición reproductiva de las hembras y proporción de hembras ovígeras o maduras en las capturas. La información provino de muestreos diarios aleatorios realizados sobre ejemplares capturados en las zonas visitadas por la flota. Para cada recurso se estableció un tamaño mínimo de muestra de 300 ejemplares. La longitud cefalotorácica fue medida con pie de metro de precisión 0,01 mm, registrándose además el peso individual, la condición del ejemplar, el sexo y, en hembras, la presencia de huevos y su grado de madurez según la escala de Palma y Arana (1997).</p>
<section id="proporción-sexual-y-talla-promedio" class="level2">
<h2 class="anchored" data-anchor-id="proporción-sexual-y-talla-promedio">3.1 Proporción sexual y talla promedio</h2>
<p>En las capturas de abril de 2026, el langostino colorado y camarón nailon presentaron una proporción sexual favorable a las hembras, las que representaron el 51 % y el 70 % del total, respectivamente. En contraste, en el langostino amarillo predominaron los machos, representando el 68 % de los ejemplares muestreados (Fig. 6).</p>
<p>En términos de talla media, el langostino colorado presentó longitudes cefalotorácicas entre 30 y 46 mm, con valores promedio similares entre sexos: 36,2 mm LC en hembras y 37,7 mm LC en machos. En perspectiva histórica, las tallas medias observadas durante 2026 se mantienen en el rango alto de la serie reciente, con promedios en torno o superiores a 36 mm LC (Fig. 7).</p>
<p>En langostino amarillo, los machos alcanzaron una talla media de 40 mm LC, superior a la registrada en hembras, que fue de 31 mm LC. Al comparar estos resultados con años anteriores, en ambos sexos se observa un repunte de las tallas en relación al mes de marzo, situándose en tallas similares a las observadas desde el año 2022 (Tabla 2, Fig. 7).</p>
<p>Por su parte, en el camarón nailon las tallas medias se situaron en torno a 30 mm LC en hembras y 28 mm LC en machos (Tabla 2). </p>
<section id="tabla-2.-proporción-sexual-y-talla-promedio-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-en-las-capturas-de-la-ups-2026" class="level5">
<h5 class="anchored" data-anchor-id="tabla-2.-proporción-sexual-y-talla-promedio-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-en-las-capturas-de-la-ups-2026"><em>Tabla 2. Proporción sexual y talla promedio de langostino colorado, langostino amarillo y camarón nailon en las capturas de la UPS, 2026</em></h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Mes</th>
<th>Sexo</th>
<th>n</th>
<th>LC(mm)</th>
<th>DE(mm)</th>
<th>Min.(mm)</th>
<th>Max.(mm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>813</td>
<td>35,9</td>
<td>2,44</td>
<td>29,8</td>
<td>43,7</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1595</td>
<td>37,0</td>
<td>2,34</td>
<td>29,9</td>
<td>46,5</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>hembra</td>
<td>1508</td>
<td>36,2</td>
<td>2,06</td>
<td>30,0</td>
<td>44,1</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1561</td>
<td>37,7</td>
<td>2,09</td>
<td>29,9</td>
<td>46,0</td>
</tr>
<tr class="odd">
<td><strong>L.amarillo</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>246</td>
<td>29,3</td>
<td>3,77</td>
<td>20,7</td>
<td>41,8</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>732</td>
<td>36,1</td>
<td>6,45</td>
<td>20,2</td>
<td>51,6</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>hembra</td>
<td>336</td>
<td>31,7</td>
<td>3,30</td>
<td>20,3</td>
<td>40,9</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>729</td>
<td>40,0</td>
<td>4,71</td>
<td>19,6</td>
<td>49,2</td>
</tr>
<tr class="odd">
<td><strong>Camarón</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>1163</td>
<td>29,9</td>
<td>2,31</td>
<td>24,3</td>
<td>36,9</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>587</td>
<td>28,7</td>
<td>1,36</td>
<td>25,0</td>
<td>33,2</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>hembra</td>
<td>700</td>
<td>30,0</td>
<td>2,48</td>
<td>23,9</td>
<td>37,6</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>300</td>
<td>28,4</td>
<td>1,47</td>
<td>25,1</td>
<td>33,4</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/prop_sexual_abril.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Proporción sexual de langostino colorado (A), langostino amarillo (B) y camarón nailon durante abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/tallas_abril.jpg" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Talla promedio (LC, mm) de langostino colorado y langostino amarillo por sexo, en el periodo enero 2016 a abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="aspectos-reproductivos" class="level2">
<h2 class="anchored" data-anchor-id="aspectos-reproductivos">3.2 Aspectos reproductivos</h2>
<p>Durante abril de 2026, el 20 % de las hembras de langostino colorado se encontró en condición ovígera, proporción superior a la registrada en marzo y similar a la observada durante el año anterior. En langostino amarillo no se registraron hembras ovígeras, manteniéndose la tendencia observada desde 2017. En camarón nailon, el 27 % de las hembras correspondió a ejemplares maduros, mientras que predominó la fracción inmadura (Tabla 3, Fig. 8).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/madurez_abril.jpg" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Hembras ovígeras de langostino colorado y langostino amarillo durante abril 2026, en comparación con la media registrada entre los años 2017 a 2024 (línea verde)</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<section id="tabla-3.-porcentaje-de-hembras-ovígeras-y-hembras-maduras-de-langostino-colorado-y-amarillo-ups-2026-y-de-hembras-portadoras-e-inmaduras-de-camarón-nailon" class="level5">
<h5 class="anchored" data-anchor-id="tabla-3.-porcentaje-de-hembras-ovígeras-y-hembras-maduras-de-langostino-colorado-y-amarillo-ups-2026-y-de-hembras-portadoras-e-inmaduras-de-camarón-nailon"><em>Tabla 3. Porcentaje de hembras ovígeras y hembras maduras de langostino colorado y amarillo UPS 2026, y de hembras portadoras e inmaduras de camarón nailon</em></h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Recurso</strong></th>
<th><strong>Estado</strong></th>
<th><strong>mar.</strong></th>
<th><strong>abr.</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>Normal</td>
<td>95%</td>
<td>79%</td>
</tr>
<tr class="even">
<td></td>
<td>Ovígeras</td>
<td>4%</td>
<td>20%</td>
</tr>
<tr class="odd">
<td></td>
<td>Madura</td>
<td>1%</td>
<td>1%</td>
</tr>
<tr class="even">
<td>Total n°</td>
<td></td>
<td>813</td>
<td>1508</td>
</tr>
<tr class="odd">
<td><strong>L.amarillo</strong></td>
<td>Normal</td>
<td>100%</td>
<td>100%</td>
</tr>
<tr class="even">
<td></td>
<td>Ovígeras</td>
<td>0%</td>
<td>0%</td>
</tr>
<tr class="odd">
<td></td>
<td>Madura</td>
<td>0%</td>
<td>0%</td>
</tr>
<tr class="even">
<td>Total n°</td>
<td></td>
<td>246</td>
<td>336</td>
</tr>
<tr class="odd">
<td><strong>C.nailon</strong></td>
<td>Inmadura</td>
<td>96%</td>
<td>73%</td>
</tr>
<tr class="even">
<td></td>
<td>Madura</td>
<td>4%</td>
<td>27%</td>
</tr>
<tr class="odd">
<td>Total n°</td>
<td></td>
<td>1221</td>
<td>700</td>
</tr>
</tbody>
</table>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="composición-de-tallas" class="level2">
<h2 class="anchored" data-anchor-id="composición-de-tallas">3.3. Composición de tallas</h2>
<p>En langostino colorado, las tallas medias fueron similares entre sexos y no se detectaron diferencias estadísticamente significativas durante abril de 2026 (prueba t de Student, p &gt; 0,05). En contraste, en langostino amarillo y camarón nailon sí se detectaron diferencias significativas entre sexos (prueba t de Student, p &lt; 0,05). En langostino amarillo, los machos presentaron una mayor talla media (40,0 mm LC) que las hembras (31,7 mm LC), mientras que en camarón nailon las hembras alcanzaron tallas medias cercanas a 30,0 mm LC, superiores a las observadas en machos (28,4 mm LC) (Tabla 2; Figs. 9–11).</p>
<p>En relación con la composición de tallas por zona de pesca, el langostino colorado mostró distribuciones de menor talla en San Vicente, mientras que las mayores tallas se registraron en Pichilemu (Fig. 12). En langostino amarillo, las tallas fueron similares entre los caladeros analizados, San Vicente e Itata (Fig. 13). En el caso del camarón nailon, las mayores tallas se observaron en Chanco, especialmente en hembras, mientras que los machos presentaron tallas similares entre los tres caladeros considerados (Fig. 14).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/frec_col_sexo_abril.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de langostino colorado entre sexos, en abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/frec_amar_sexo_abril.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de langostino amarillo entre sexos, en abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/frec_cam_sexo_abril.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de camarón nailon entre sexos, en abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/frec_col_zona_abril.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Composición de tallas de langostino colorado en la UPS por zonas de pesca en abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/frec_am_zona_abril.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Composición de tallas de langostino amarillo en la UPS por zonas de pesca en abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/frec_cam_zona_abril.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Composición de tallas de camarón nailon en la UPS por zonas de pesca en abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="fauna-acompañante" class="level2">
<h2 class="anchored" data-anchor-id="fauna-acompañante">3.4 Fauna acompañante</h2>
<p>Durante abril de 2026, las operaciones de pesca de la flota de CrustaSur registraron presencia de pejerrata como fauna acompañante en los caladeros de Carranza, Chanco e Itata (Fig. 15). Esta especie representó el 1,9 % del total capturado, con un volumen aproximado de 9 toneladas. Entre los otros recursos registrados como fauna acompañante destacaron merluza y lenguado, presentes en varios de los caladeros visitados, con rendimientos entre 15 y 100 kg/ha. También se registró presencia de jaiba paco y jaiba limón, aunque en menor magnitud, expresada en unidades por hora de arrastre (Fig. 16).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/pejerrata_abril.jpeg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de los lances de pesca con captura de pejerrata y proporción relativa de pejerrata en las capturas totales durante abril del año 2026.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_abril_26/fauna_Acomp_abril.jpeg" class="img-fluid figure-img" style="width:110.0%"></p>
<figcaption>Distribución espacial y abundancia de la fauna acompañante en los lances de pesca orientados a langostinos colorado y langostino amarillo por la flota arrastrera de CrustaSur, abril de 2026</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>