<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bol.Tec.11(2)|Lab.EPOMAR(UdeC)|CRUSTASUR">

<title>Indicadores biológico-pesqueros de langostino colorado y langostino amarillo, (mayo 2026)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="BolTec1103_files/libs/clipboard/clipboard.min.js"></script>
<script src="BolTec1103_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="BolTec1103_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="BolTec1103_files/libs/quarto-html/popper.min.js"></script>
<script src="BolTec1103_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BolTec1103_files/libs/quarto-html/anchor.min.js"></script>
<link href="BolTec1103_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BolTec1103_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BolTec1103_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BolTec1103_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BolTec1103_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">1 Resumen</a></li>
  <li><a href="#aspectos-pesqueros" id="toc-aspectos-pesqueros" class="nav-link" data-scroll-target="#aspectos-pesqueros">2 Aspectos Pesqueros</a>
  <ul class="collapse">
  <li><a href="#actividad-pesquera" id="toc-actividad-pesquera" class="nav-link" data-scroll-target="#actividad-pesquera">2.1 Actividad pesquera</a></li>
  <li><a href="#captura-esfuerzo-y-rendimientos-de-pesca" id="toc-captura-esfuerzo-y-rendimientos-de-pesca" class="nav-link" data-scroll-target="#captura-esfuerzo-y-rendimientos-de-pesca">2.2 Captura, esfuerzo y rendimientos de pesca</a></li>
  </ul></li>
  <li><a href="#aspectos-biológicos" id="toc-aspectos-biológicos" class="nav-link" data-scroll-target="#aspectos-biológicos">3 Aspectos biológicos</a>
  <ul class="collapse">
  <li><a href="#proporción-sexual-y-talla-promedio" id="toc-proporción-sexual-y-talla-promedio" class="nav-link" data-scroll-target="#proporción-sexual-y-talla-promedio">3.1 Proporción sexual y talla promedio</a></li>
  <li><a href="#aspectos-reproductivos" id="toc-aspectos-reproductivos" class="nav-link" data-scroll-target="#aspectos-reproductivos">3.2 Aspectos reproductivos</a></li>
  <li><a href="#composición-de-tallas" id="toc-composición-de-tallas" class="nav-link" data-scroll-target="#composición-de-tallas">3.3. Composición de tallas</a></li>
  <li><a href="#fauna-acompañante" id="toc-fauna-acompañante" class="nav-link" data-scroll-target="#fauna-acompañante">3.4 Fauna acompañante</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Indicadores biológico-pesqueros de langostino colorado y langostino amarillo, (mayo 2026)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bol.Tec.11(2)|Lab.EPOMAR(UdeC)|CRUSTASUR </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div style="page-break-after: always;"></div>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">1 Resumen</h2>
<p>La actividad pesquera de la flota de CrustaSur se desarrolló entre las regiones del Biobío y del Libertador General Bernardo O’Higgins, abarcando principalmente los caladeros de Itata, Achira, Los Maquis, Nogurne, Carranza, Constitución, Pichilemu y Topocalma. La operación estuvo dominada por lances con captura de langostino colorado y por lances mixtos de langostino colorado y langostino amarillo.</p>
<p>En términos operacionales, el langostino colorado registró la mayor captura mensual, alcanzando 552 toneladas, con un rendimiento promedio de 1666 kg/ha. Por su parte, el langostino amarillo registró 41 toneladas de captura y un rendimiento promedio de 238 kg/ha. El camarón nailon presentó una menor representación relativa dentro de la operación mensual, por lo que no se reportan indicadores operacionales específicos para este recurso en mayo.</p>
<p>Desde el punto de vista biológico, el langostino colorado presentó una proporción sexual favorable a las hembras, mientras que en langostino amarillo predominaron ampliamente los machos. Las tallas medias de langostino colorado se mantuvieron en torno a 35–36 mm LC, con valores levemente superiores en machos. En langostino amarillo, los machos alcanzaron una talla media de 37,3 mm LC, superior a la registrada en hembras, que fue de 32,7 mm LC.</p>
<p>En relación con los aspectos reproductivos, el 65 % de las hembras de langostino colorado se encontró en condición ovígera, proporción superior a la registrada en abril. En langostino amarillo no se observó presencia de hembras ovígeras, manteniéndose la tendencia descrita desde 2017.</p>
<p>La composición de tallas mostró diferencias entre recursos y zonas de pesca. En langostino colorado, las mayores tallas se observaron principalmente en Pichilemu e Itata, mientras que en langostino amarillo las distribuciones de talla fueron relativamente similares entre los caladeros analizados. Finalmente, la fauna acompañante estuvo representada principalmente por pejerrata, merluza, lenguado, jaiba paco y jaiba limón, con baja participación relativa respecto de las capturas objetivo.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="aspectos-pesqueros" class="level1">
<h1>2 Aspectos Pesqueros</h1>
<section id="actividad-pesquera" class="level2">
<h2 class="anchored" data-anchor-id="actividad-pesquera">2.1 Actividad pesquera</h2>
<p>La distribución espacial de los lances muestra una operación concentrada en sectores costeros discretos, asociados a caladeros históricamente relevantes para la pesquería de crustáceos demersales. Durante mayo de 2026, la actividad se desarrolló desde la región del Biobío hasta la región del Libertador General Bernardo O’Higgins, destacando los caladeros de Pichilemu, Topocalma, Constitución, Carranza, Nogurne, Achira, Los Maquis e Itata (Fig. 1).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/lances_mayo.jpeg" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Distribución espacial del total de lances de pesca realizados durante mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="captura-esfuerzo-y-rendimientos-de-pesca" class="level2">
<h2 class="anchored" data-anchor-id="captura-esfuerzo-y-rendimientos-de-pesca">2.2 Captura, esfuerzo y rendimientos de pesca</h2>
<p>La actividad pesquera se concentró principalmente en lances con captura de langostino colorado y en lances mixtos de langostino colorado y langostino amarillo. En cuanto a la distribución espacial de las capturas por recurso, el langostino colorado presentó una amplia cobertura en los caladeros visitados, mientras que el langostino amarillo se registró principalmente en sectores asociados a Itata, Achira, Los Maquis, Nogurne y Constitución. El camarón nailon presentó menor representación relativa dentro de la operación mensual, concentrándose en sectores específicos de la zona centro-sur (Fig. 2).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/lances_especie-mayo.jpeg" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Distribución espacial de los lances de pesca orientados a langostino colorado, langostino amarillo y camarón nailon durante mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<p>El langostino colorado registró la mayor captura mensual, alcanzando 552 toneladas, con un promedio de 2653 kg por lance, un esfuerzo total de 331 horas de arrastre y un rendimiento promedio de 1666 kg/ha (Tabla 1). Para langostino amarillo, se registraron 107 lances, una captura total de 41 toneladas, un promedio de 383 kg por lance, un esfuerzo total de 172 horas de arrastre y un rendimiento promedio de 238 kg/ha.</p>
<div style="page-break-after: always;"></div>
<section id="tabla-1.-indicadores-operacionales-de-la-pesquería-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-año-2026." class="level5">
<h5 class="anchored" data-anchor-id="tabla-1.-indicadores-operacionales-de-la-pesquería-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-año-2026."><em>Tabla 1. Indicadores operacionales de la pesquería de langostino colorado, langostino amarillo y camarón nailon, año 2026.</em></h5>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Recurso</strong></th>
<th><strong>Mes</strong></th>
<th><strong>N° de lances(n)</strong></th>
<th><strong>Cap. (kg)</strong></th>
<th><strong>Cap.lances (kg/n)</strong></th>
<th><strong>h arrast.(ha)</strong></th>
<th><strong>Rend. (kg/ha)</strong></th>
<th><strong>Prof.de fondo(m)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>marzo</td>
<td>137</td>
<td>351754</td>
<td>2567</td>
<td>121</td>
<td>2907</td>
<td>249</td>
</tr>
<tr class="even">
<td></td>
<td>abril</td>
<td>162</td>
<td>384280</td>
<td>2372</td>
<td>230</td>
<td>1281</td>
<td>224</td>
</tr>
<tr class="odd">
<td></td>
<td>mayo</td>
<td>208</td>
<td>552006</td>
<td>2653</td>
<td>331</td>
<td>1666</td>
<td>189</td>
</tr>
<tr class="even">
<td><strong>L.amarillo</strong></td>
<td>marzo</td>
<td>83</td>
<td>42789</td>
<td>515</td>
<td>49</td>
<td>877</td>
<td>264</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>86</td>
<td>48702</td>
<td>566</td>
<td>138</td>
<td>352</td>
<td>238</td>
</tr>
<tr class="even">
<td></td>
<td>mayo</td>
<td>107</td>
<td>41075</td>
<td>383</td>
<td>172</td>
<td>238</td>
<td>186</td>
</tr>
<tr class="odd">
<td><strong>Camarón</strong></td>
<td>marzo</td>
<td>57</td>
<td>98820</td>
<td>1733</td>
<td>87</td>
<td>1138</td>
<td>324</td>
</tr>
<tr class="even">
<td></td>
<td>abril</td>
<td>37</td>
<td>46825</td>
<td>1265</td>
<td>67</td>
<td>693</td>
<td>283</td>
</tr>
</tbody>
</table>
<p>El rendimiento promedio de pesca del langostino colorado fue de 1666 kg/ha, con un esfuerzo total de 331 horas de arrastre y un promedio de 2653 kg por lance. En langostino amarillo, el rendimiento promedio fue de 238 kg/ha, con un esfuerzo total de 172 horas de arrastre y un promedio de 383 kg por lance (Tabla 1; Fig. 3). Estos resultados muestran que, durante mayo, el langostino colorado concentró la mayor captura y los mayores rendimientos promedio dentro de los recursos analizados.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/esf_rend_mayo.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de frecuencia del esfuerzo de pesca (en horas de arrastre, A) y del rendimiento (en kg/ha, B), para langostino colorado, langostino amarillo y camarón nailon durante mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<p>Los mayores rendimientos de langostino colorado se observaron principalmente en los caladeros de Itata, Achira, Los Maquis y Pichilemu, con una alta variabilidad espacial entre lances (Fig. 4,5). En langostino amarillo, los mayores rendimientos se registraron principalmente en los caladeros de Nogurne y Los Maquis, mientras que en el resto de los sectores los valores fueron comparativamente menores (Fig. 4,5).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/cpue_espec_mayo.jpeg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Rendimiento de pesca (captura por hora de arrastre) de langostino colorado (A), langostino amarillo (B) y camarón nailon (C), en mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/redim_caladero_mayo.jpg" class="img-fluid figure-img" style="width:110.0%"></p>
<figcaption>Distribución del rendimiento de pesca (kg/ha) de langostino colorado, langostino amarillo y camarón nailon en mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="aspectos-biológicos" class="level1">
<h1>3 Aspectos biológicos</h1>
<p>Los indicadores biológicos considerados incluyeron la talla promedio por sexo, proporción sexual, estructura de tallas, condición reproductiva de las hembras y proporción de hembras ovígeras o maduras en las capturas. La información provino de muestreos diarios aleatorios realizados sobre ejemplares capturados en las zonas visitadas por la flota. Para cada recurso se estableció un tamaño mínimo de muestra de 300 ejemplares. La longitud cefalotorácica fue medida con pie de metro de precisión 0,01 mm, registrándose además el peso individual, la condición del ejemplar, el sexo y, en hembras, la presencia de huevos y su grado de madurez según la escala de Palma y Arana (1997).</p>
<section id="proporción-sexual-y-talla-promedio" class="level2">
<h2 class="anchored" data-anchor-id="proporción-sexual-y-talla-promedio">3.1 Proporción sexual y talla promedio</h2>
<p>En las capturas de mayo de 2026, el langostino colorado presentó una proporción sexual favorable a las hembras, mientras que en langostino amarillo predominaron ampliamente los machos (Fig. 6).</p>
<p>En términos de talla media, el langostino colorado presentó longitudes cefalotorácicas entre 27,0 y 47,4 mm, con valores promedio de 35,3 mm LC en hembras y 36,4 mm LC en machos. En perspectiva histórica, las tallas medias observadas durante 2026 se mantienen dentro del rango reciente de la serie, con promedios cercanos o superiores a 35 mm LC (Tabla 2; Fig. 7).</p>
<p>En langostino amarillo, los machos alcanzaron una talla media de 37,3 mm LC, superior a la registrada en hembras, que fue de 32,7 mm LC. Las tallas observadas durante mayo se mantuvieron dentro del rango registrado en la serie reciente, con una marcada diferencia entre sexos, asociada a la mayor talla promedio de los machos (Tabla 2; Fig. 7). </p>
<section id="tabla-2.-proporción-sexual-y-talla-promedio-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-en-las-capturas-de-la-ups-2026" class="level5">
<h5 class="anchored" data-anchor-id="tabla-2.-proporción-sexual-y-talla-promedio-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-en-las-capturas-de-la-ups-2026"><em>Tabla 2. Proporción sexual y talla promedio de langostino colorado, langostino amarillo y camarón nailon en las capturas de la UPS, 2026</em></h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Mes</th>
<th>Sexo</th>
<th>n</th>
<th>LC(mm)</th>
<th>DE(mm)</th>
<th>Min.(mm)</th>
<th>Max.(mm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>813</td>
<td>35,9</td>
<td>2,44</td>
<td>29,8</td>
<td>43,7</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1595</td>
<td>37,0</td>
<td>2,34</td>
<td>29,9</td>
<td>46,5</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>hembra</td>
<td>1508</td>
<td>36,2</td>
<td>2,06</td>
<td>30,0</td>
<td>44,1</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1561</td>
<td>37,7</td>
<td>2,09</td>
<td>29,9</td>
<td>46,0</td>
</tr>
<tr class="odd">
<td></td>
<td>mayo</td>
<td>hembra</td>
<td>2374</td>
<td>35,3</td>
<td>2,26</td>
<td>27,0</td>
<td>43,4</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1219</td>
<td>36,4</td>
<td>2,53</td>
<td>28,9</td>
<td>47,4</td>
</tr>
<tr class="odd">
<td><strong>L.amarillo</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>246</td>
<td>29,3</td>
<td>3,77</td>
<td>20,7</td>
<td>41,8</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>732</td>
<td>36,1</td>
<td>6,45</td>
<td>20,2</td>
<td>51,6</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>hembra</td>
<td>336</td>
<td>31,7</td>
<td>3,30</td>
<td>20,3</td>
<td>40,9</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>729</td>
<td>40,0</td>
<td>4,71</td>
<td>19,6</td>
<td>49,2</td>
</tr>
<tr class="odd">
<td></td>
<td>mayo</td>
<td>hembra</td>
<td>164</td>
<td>32,7</td>
<td>2,65</td>
<td>26,9</td>
<td>41,0</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1363</td>
<td>37,3</td>
<td>4,43</td>
<td>25,2</td>
<td>48,3</td>
</tr>
<tr class="odd">
<td><strong>Camarón</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>1163</td>
<td>29,9</td>
<td>2,31</td>
<td>24,3</td>
<td>36,9</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>587</td>
<td>28,7</td>
<td>1,36</td>
<td>25,0</td>
<td>33,2</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>hembra</td>
<td>700</td>
<td>30,0</td>
<td>2,48</td>
<td>23,9</td>
<td>37,6</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>300</td>
<td>28,4</td>
<td>1,47</td>
<td>25,1</td>
<td>33,4</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/proporcion_sexual_MAYO.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Proporción sexual de langostino colorado (A) y langostino amarillo (B) durante mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/GRAFICAS_TALLAS_2026_MAYO.jpg" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Talla promedio (LC, mm) de langostino colorado y langostino amarillo por sexo, en el periodo enero 2016 a mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="aspectos-reproductivos" class="level2">
<h2 class="anchored" data-anchor-id="aspectos-reproductivos">3.2 Aspectos reproductivos</h2>
<p>Durante mayo de 2026, el 65 % de las hembras de langostino colorado se encontró en condición ovígera, constituyendo la fracción predominante dentro de las hembras muestreadas. En langostino amarillo no se registraron hembras ovígeras ni maduras, manteniéndose el predominio de hembras en condición normal observado durante el periodo analizado (Tabla 3; Fig. 8).</p>
<p>Al analizar la distribución espacial de la condición ovígera en langostino colorado, se observaron diferencias entre caladeros. En mayo de 2026, los mayores porcentajes de hembras ovígeras se registraron en Pichilemu, Achira e Itata, con valores superiores al 90 %. Sin embargo, en algunos caladeros el porcentaje de hembras ovígeras fue menor respecto del histórico 2024–2025, destacando Los Maquis y Chanco, donde se registraron valores de 46,1 % y 56,7 %, respectivamente. Estos resultados sugieren una marcada variabilidad espacial en la condición reproductiva durante el periodo analizado (Fig. 9).</p>
<section id="tabla-3.-porcentaje-de-hembras-ovígeras-y-hembras-maduras-de-langostino-colorado-y-amarillo-ups-2026-y-de-hembras-portadoras-e-inmaduras-de-camarón-nailon" class="level5">
<h5 class="anchored" data-anchor-id="tabla-3.-porcentaje-de-hembras-ovígeras-y-hembras-maduras-de-langostino-colorado-y-amarillo-ups-2026-y-de-hembras-portadoras-e-inmaduras-de-camarón-nailon"><em>Tabla 3. Porcentaje de hembras ovígeras y hembras maduras de langostino colorado y amarillo UPS 2026, y de hembras portadoras e inmaduras de camarón nailon</em></h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Recurso</strong></th>
<th><strong>Estado</strong></th>
<th><strong>mar.</strong></th>
<th><strong>abr.</strong></th>
<th><strong>may.</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>Normal</td>
<td>95%</td>
<td>79%</td>
<td>35%</td>
</tr>
<tr class="even">
<td></td>
<td>Ovígeras</td>
<td>4%</td>
<td>20%</td>
<td>65%</td>
</tr>
<tr class="odd">
<td></td>
<td>Madura</td>
<td>1%</td>
<td>1%</td>
<td>0,1%</td>
</tr>
<tr class="even">
<td>Total n°</td>
<td></td>
<td>813</td>
<td>1508</td>
<td>2374</td>
</tr>
<tr class="odd">
<td><strong>L.amarillo</strong></td>
<td>Normal</td>
<td>100%</td>
<td>100%</td>
<td>100%</td>
</tr>
<tr class="even">
<td></td>
<td>Ovígeras</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
</tr>
<tr class="odd">
<td></td>
<td>Madura</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
</tr>
<tr class="even">
<td>Total n°</td>
<td></td>
<td>246</td>
<td>336</td>
<td>164</td>
</tr>
<tr class="odd">
<td><strong>C.nailon</strong></td>
<td>Inmadura</td>
<td>96%</td>
<td>73%</td>
<td>-</td>
</tr>
<tr class="even">
<td></td>
<td>Madura</td>
<td>4%</td>
<td>27%</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Total n°</td>
<td></td>
<td>1221</td>
<td>700</td>
<td>-</td>
</tr>
</tbody>
</table>
<div style="page-break-after: always;"></div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/madurez_MAYO-2026.jpg" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Hembras ovígeras de langostino colorado y langostino amarillo durante mayo de 2026, en comparación con la media registrada entre los años 2017 a 2024 (línea verde).</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/LC_ovigeras_mayo_historico_vs_MAYO2026.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Porcentaje de hembras ovígeras de langostino colorado por caladero en mayo de 2026 y comparación con el histórico 2024–2025. El valor n corresponde al número de hembras analizadas por celda</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="composición-de-tallas" class="level2">
<h2 class="anchored" data-anchor-id="composición-de-tallas">3.3. Composición de tallas</h2>
<p>En langostino colorado, las tallas medias fueron levemente superiores en machos respecto de hembras durante mayo de 2026. Los machos alcanzaron una talla media de 36,4 mm LC, mientras que las hembras registraron 35,3 mm LC. En langostino amarillo, se observó una diferencia más marcada entre sexos, con una talla media de 37,3 mm LC en machos y 32,7 mm LC en hembras (Tabla 2; Figs. 10–11).</p>
<p>En relación con la composición de tallas por zona de pesca, el langostino colorado mostró variabilidad espacial entre los caladeros analizados durante mayo, con distribuciones de talla que reflejan diferencias en la estructura de las capturas por zona (Fig. 12). En langostino amarillo, las distribuciones de talla también presentaron variación entre caladeros, aunque manteniendo el patrón general de mayores tallas en machos respecto de hembras (Fig. 13).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/frec_colorado_sexo_mayo.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de langostino colorado entre sexos, en mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/frec_amarillo_sexo_mayo.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de langostino amarillo entre sexos, en mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/frec_l.colorado_mayo.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Composición de tallas de langostino colorado en la UPS por zonas de pesca en mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/frec_AMARILLO_zona_MAYO.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Composición de tallas de langostino amarillo en la UPS por zonas de pesca en mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="fauna-acompañante" class="level2">
<h2 class="anchored" data-anchor-id="fauna-acompañante">3.4 Fauna acompañante</h2>
<p>Durante mayo de 2026, las operaciones de pesca de la flota de CrustaSur registraron presencia de pejerrata como fauna acompañante en distintos caladeros visitados durante la operación mensual (Fig. 14). Entre los otros recursos registrados como fauna acompañante destacaron merluza, lenguado, jaiba paco y jaiba limón, aunque con baja participación relativa respecto de las capturas objetivo. La distribución espacial y abundancia de estas especies mostró variabilidad entre caladeros, asociada a la operación de la flota sobre langostino colorado y langostino amarillo durante mayo (Fig. 15).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/pejerrata_mayo.jpeg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de los lances de pesca con captura de pejerrata y proporción relativa de pejerrata en las capturas totales durante mayo del año 2026.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_mayo_26/fauna_Acomp_mayo.jpeg" class="img-fluid figure-img" style="width:110.0%"></p>
<figcaption>Distribución espacial y abundancia de la fauna acompañante en los lances de pesca orientados a langostinos colorado y langostino amarillo por la flota arrastrera de CrustaSur, mayo de 2026</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>