<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bol.Tec.10(6)|Lab.EPOMAR Udec-Crustáceos Pesca Sur">

<title>Indicadores biológico-pesqueros de langostino colorado, langostino amarillo y camarón nailon, (agosto 2025)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="BolTec1006_files/libs/clipboard/clipboard.min.js"></script>
<script src="BolTec1006_files/libs/quarto-html/quarto.js"></script>
<script src="BolTec1006_files/libs/quarto-html/popper.min.js"></script>
<script src="BolTec1006_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BolTec1006_files/libs/quarto-html/anchor.min.js"></script>
<link href="BolTec1006_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BolTec1006_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BolTec1006_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BolTec1006_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BolTec1006_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">1 Resumen</a></li>
  <li><a href="#aspectos-pesqueros" id="toc-aspectos-pesqueros" class="nav-link" data-scroll-target="#aspectos-pesqueros">2 Aspectos Pesqueros</a>
  <ul class="collapse">
  <li><a href="#actividad-pesquera" id="toc-actividad-pesquera" class="nav-link" data-scroll-target="#actividad-pesquera">2.1 Actividad pesquera</a></li>
  <li><a href="#capturaesfuerzo-y-rendimientos-de-pesca" id="toc-capturaesfuerzo-y-rendimientos-de-pesca" class="nav-link" data-scroll-target="#capturaesfuerzo-y-rendimientos-de-pesca">2.2 Captura,esfuerzo y rendimientos de pesca</a></li>
  </ul></li>
  <li><a href="#aspectos-biológicos" id="toc-aspectos-biológicos" class="nav-link" data-scroll-target="#aspectos-biológicos">3 Aspectos biológicos</a>
  <ul class="collapse">
  <li><a href="#proporción-sexual-y-talla-promedio" id="toc-proporción-sexual-y-talla-promedio" class="nav-link" data-scroll-target="#proporción-sexual-y-talla-promedio">3.1 Proporción sexual y talla promedio</a></li>
  <li><a href="#aspectos-reproductivos" id="toc-aspectos-reproductivos" class="nav-link" data-scroll-target="#aspectos-reproductivos">3.2 Aspectos reproductivos</a></li>
  <li><a href="#composición-de-tallas" id="toc-composición-de-tallas" class="nav-link" data-scroll-target="#composición-de-tallas">3.3. Composición de tallas</a></li>
  <li><a href="#fauna-acompañante" id="toc-fauna-acompañante" class="nav-link" data-scroll-target="#fauna-acompañante">3.4 Fauna acompañante</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Indicadores biológico-pesqueros de langostino colorado, langostino amarillo y camarón nailon, (agosto 2025)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bol.Tec.10(6)|Lab.EPOMAR Udec-Crustáceos Pesca Sur </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div style="page-break-after: always;"></div>
<section id="resumen" class="level1">
<h1>1 Resumen</h1>
<p>Durante agosto de 2025, la flota arrastrera de Camanchaca Pesca Sur operó entre las regiones del Biobío y Valparaíso, concentrando su actividad en los caladeros de Algarrobo, Pichilemu y Chanco. La pesquería se dirigió principalmente al langostino colorado, con un 79 % de los lances orientados exclusivamente a este recurso, mientras que en menor proporción el esfuerzo se orientó al camarón nailon y al langostino amarillo, tanto en lances exclusivos como mixtos. El langostino colorado alcanzó capturas totales cercanas a 632 toneladas y rendimientos promedio del orden de 214 kg/ha, con los mayores valores en Algarrobo y Carranza; el camarón nailon se concentró en Chanco y el langostino amarillo presentó los mayores rendimientos en isla Santa María.</p>
<p>En términos biológicos, predominó la presencia de hembras en langostino colorado y camarón nailon, con tallas medias en torno a 37 mm de longitud del caparazón (LC) y 27,5 mm LC, respectivamente. Para langostino colorado se observó una alta proporción de hembras ovígeras (≈78 %), consistente con un ciclo reproductivo adelantado respecto del promedio histórico. La fauna acompañante estuvo dominada por merluza, lenguado y, en menor proporción, pejerrata y jaibas.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="aspectos-pesqueros" class="level1">
<h1>2 Aspectos Pesqueros</h1>
<section id="actividad-pesquera" class="level2">
<h2 class="anchored" data-anchor-id="actividad-pesquera">2.1 Actividad pesquera</h2>
<p>Las operaciones de pesca realizadas durante agosto cubrieron los caladeros ubicados desde la región del Bío-Bío a la región de Valparaíso, destacando los caladeros del Algarrobo, Pichilemu y Chanco (Fig. 1).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/agosto_2025.jpeg" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Distribución espacial del total de lances de pesca realizados durante agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="capturaesfuerzo-y-rendimientos-de-pesca" class="level2">
<h2 class="anchored" data-anchor-id="capturaesfuerzo-y-rendimientos-de-pesca">2.2 Captura,esfuerzo y rendimientos de pesca</h2>
<p>Durante agosto de 2025, la actividad pesquera se centró principalmente en el langostino colorado. El 79 % de los lances se dirigió exclusivamente al langostino colorado, mientras que un 10 % correspondió a capturas exclusivas de camarón nailon. Otro 10 % se orientó a capturas mixtas de langostino colorado y langostino amarillo, y el 1,5 % restante a capturas exclusivas de langostino amarillo (Fig. 2).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/lances_especie_agosto.jpeg" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Distribución espacial de los lances de pesca orientados a langostino colorado, langostino amarillo y camarón nailon durante agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<p>Las capturas por lance de langostino colorado variaron entre 0 y 10 ton, alcanzando un total de 631 toneladas. El promedio por lance fue de 3530 kg/lance, con un esfuerzo total de 294 horas de arrastre (ha) y un rendimiento de pesca de 214 kg/ha (Tabla 1). En el caso del langostino amarillo, se registraron 19 lances que sumaron un total de 22 toneladas, con un rendimiento promedio de 663 kg/ha. Por su parte, el camarón nailon fue capturado en 47 lances, alcanzando una captura total de 41 toneladas y un rendimiento de 337 kg/ha (Tabla 1).</p>
<div style="page-break-after: always;"></div>
<section id="tabla-1.-indicadores-operacionales-de-la-pesquería-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-año-2025." class="level5">
<h5 class="anchored" data-anchor-id="tabla-1.-indicadores-operacionales-de-la-pesquería-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-año-2025."><em>Tabla 1. Indicadores operacionales de la pesquería de langostino colorado, langostino amarillo y camarón nailon, año 2025.</em></h5>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Recurso</strong></th>
<th><strong>Mes</strong></th>
<th><strong>N° de lances(n)</strong></th>
<th><strong>Cap. (kg)</strong></th>
<th><strong>Cap.lances (kg/n)</strong></th>
<th><strong>h arrast.(ha)</strong></th>
<th><strong>Rend. (kg/ha)</strong></th>
<th><strong>Prof.de fondo(m)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>marzo</td>
<td>178</td>
<td>492941</td>
<td>2769</td>
<td>233</td>
<td>2118</td>
<td>220</td>
</tr>
<tr class="even">
<td></td>
<td>abril</td>
<td>267</td>
<td>805486</td>
<td>3017</td>
<td>366</td>
<td>2202</td>
<td>210</td>
</tr>
<tr class="odd">
<td></td>
<td>mayo</td>
<td>254</td>
<td>792701</td>
<td>3121</td>
<td>513</td>
<td>1546</td>
<td>177</td>
</tr>
<tr class="even">
<td></td>
<td>junio</td>
<td>205</td>
<td>722214</td>
<td>3523</td>
<td>460</td>
<td>1571</td>
<td>163</td>
</tr>
<tr class="odd">
<td></td>
<td>julio</td>
<td>210</td>
<td>736028</td>
<td>3504</td>
<td>487</td>
<td>1510</td>
<td>157</td>
</tr>
<tr class="even">
<td></td>
<td>agosto</td>
<td>179</td>
<td>631958</td>
<td>3530</td>
<td>294</td>
<td>214</td>
<td>192</td>
</tr>
<tr class="odd">
<td><strong>L.amarillo</strong></td>
<td>marzo</td>
<td>124</td>
<td>102458</td>
<td>826</td>
<td>172</td>
<td>596</td>
<td>225</td>
</tr>
<tr class="even">
<td></td>
<td>abril</td>
<td>200</td>
<td>89582</td>
<td>448</td>
<td>273</td>
<td>328</td>
<td>215</td>
</tr>
<tr class="odd">
<td></td>
<td>mayo</td>
<td>138</td>
<td>55002</td>
<td>399</td>
<td>280</td>
<td>197</td>
<td>167</td>
</tr>
<tr class="even">
<td></td>
<td>junio</td>
<td>47</td>
<td>5796</td>
<td>123</td>
<td>104</td>
<td>55</td>
<td>156</td>
</tr>
<tr class="odd">
<td></td>
<td>julio</td>
<td>75</td>
<td>112455</td>
<td>1499</td>
<td>167</td>
<td>693</td>
<td>178</td>
</tr>
<tr class="even">
<td></td>
<td>agosto</td>
<td>19</td>
<td>22212</td>
<td>1169</td>
<td>33</td>
<td>663</td>
<td>193</td>
</tr>
<tr class="odd">
<td><strong>Camarón</strong></td>
<td>marzo</td>
<td>44</td>
<td>30862</td>
<td>702</td>
<td>87</td>
<td>352</td>
<td>301</td>
</tr>
<tr class="even">
<td></td>
<td>abril</td>
<td>7</td>
<td>1048</td>
<td>149</td>
<td>7</td>
<td>153</td>
<td>223</td>
</tr>
<tr class="odd">
<td></td>
<td>mayo</td>
<td>8</td>
<td>128</td>
<td>16</td>
<td>13</td>
<td>10</td>
<td>188</td>
</tr>
<tr class="even">
<td></td>
<td>junio</td>
<td>8</td>
<td>18080</td>
<td>2260</td>
<td>19</td>
<td>933</td>
<td>315</td>
</tr>
<tr class="odd">
<td></td>
<td>julio</td>
<td>12</td>
<td>315</td>
<td>26</td>
<td>22</td>
<td>14</td>
<td>178</td>
</tr>
<tr class="even">
<td></td>
<td>agosto</td>
<td>47</td>
<td>41462</td>
<td>882</td>
<td>123</td>
<td>337</td>
<td>278</td>
</tr>
</tbody>
</table>
<p>El rendimiento de pesca del langostino colorado osciló entre 14 y 12891 kg/ha, con una moda de 1955 kg/ha. El esfuerzo por lance varió entre 0 y 200 minutos, concentrándose mayoritariamente en torno a 1 horas y 35 minutos (Fig. 3). En el caso del langostino amarillo, el rendimiento fluctuó entre 6 y 663 kg/ha, con un esfuerzo predominante cercano a 1 horas y 50 minutos. Por su parte, el camarón nailon alcanzó un rendimiento máximo de 337 kg/ha, concentrando su esfuerzo principalmente en torno a 2 horas y 30 minutos (Fig. 3).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/esf_rend_agosto.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de frecuencia del esfuerzo de pesca (en horas de arrastre, A) y del rendimiento (en kg/ha, B), para langostino colorado y langostino amarillo durante agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<p>En cuanto a la distribución espacial del rendimiento de pesca durante agosto, destacaron los caladeros de Algarrobo y Carranza por sus altos rendimientos de langostino colorado, con promedios entre 1500 y 5000 kg/ha (Fig. 4 y 5). En el caso del camarón nailon, las capturas se concentraron exclusivamente en el caladero de Chanco, con rendimientos entre 200 y 700 kg/ha. Para el langostino amarillo, los mayores rendimientos se observaron en la isla Sta. María, con valores entre 2000 y 5000 kg/ha (Fig. 4 y 5).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/cpue_espec_agosto.jpeg" class="img-fluid figure-img" style="width:110.0%"></p>
<figcaption>Distribución del rendimiento de pesca (kg/ha) de langostino colorado, langostino amarillo y camarón nailon en agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/caladeros_agosto.jpg" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Rendimiento de pesca (captura por hora de arrastre) anual de langostino colorado (A), langostino amarillo (B) y camarón nailon (C), en los caladeros visitados de en la unidad de pesquería sur, agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="aspectos-biológicos" class="level1">
<h1>3 Aspectos biológicos</h1>
<p>Los indicadores biológicos incluyen la talla promedio por sexo, proporción sexual, estructura de tallas, estado de madurez de las hembras ovígeras y su proporción en las capturas. Los datos fueron obtenidos a partir de muestreos diarios aleatorios realizados sobre ejemplares capturados en las zonas visitadas por la flota. Se estableció un tamaño mínimo de muestra de 300 ejemplares, midiendo la longitud del cefalótorax con una precisión de 0,01 mm mediante un pie de metro. Además, los individuos fueron pesados (precisión 0,01 g), y se registró si estaban completos o incompletos. Se determinó el sexo de cada ejemplar y, en el caso de las hembras, se consignó la presencia de huevos (estado ovígero) y el grado de madurez de los mismos, según la escala de 4 puntos propuesta por Palma y Arana (1997).</p>
<section id="proporción-sexual-y-talla-promedio" class="level2">
<h2 class="anchored" data-anchor-id="proporción-sexual-y-talla-promedio">3.1 Proporción sexual y talla promedio</h2>
<p>Durante las capturas de agosto de 2025, el langostino colorado y camarón nailon presentó una proporción sexual favorable a las hembras, con 77% y 81% respectivamente (Fig. 6,7).</p>
<p>En cuanto a las tallas promedio, el langostino colorado presentó longitudes cefalotorácicas entre 23 y 48 mm, con promedios de 37,3 mm en machos y 36,4 mm en hembras. En comparación con temporadas anteriores, las tallas medias registradas a comienzos de este año fueron particularmente altas, superando los 37 mm LC. Posteriormente, disminuyeron en junio, volvieron a incrementarse en julio y se mantuvieron sobre los 36 mm LC durante agosto (Fig. 7). En el caso del camarón nailon, las hembras presentaron las mayores tallas promedio (27,5 mm LC), frente a los 24 mm LC observados en los machos. Para el langostino amarillo no se contó con muestreo biológico durante agosto, por lo que no fue posible realizar este análisis.</p>
<section id="tabla-2.-proporción-sexual-y-talla-promedio-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-en-las-capturas-de-la-ups-año-2025" class="level5">
<h5 class="anchored" data-anchor-id="tabla-2.-proporción-sexual-y-talla-promedio-de-langostino-colorado-langostino-amarillo-y-camarón-nailon-en-las-capturas-de-la-ups-año-2025"><em>Tabla 2. Proporción sexual y talla promedio de langostino colorado, langostino amarillo y camarón nailon en las capturas de la UPS, año 2025</em></h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Mes</th>
<th>Sexo</th>
<th>n</th>
<th>LC(mm)</th>
<th>DE(mm)</th>
<th>Min.(mm)</th>
<th>Max.(mm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>1590</td>
<td>38,2</td>
<td>2,66</td>
<td>24.6</td>
<td>44,7</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1316</td>
<td>37,9</td>
<td>4,09</td>
<td>25,6</td>
<td>46,4</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>hembra</td>
<td>2037</td>
<td>35,2</td>
<td>2,33</td>
<td>22,3</td>
<td>42,6</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>2337</td>
<td>37,1</td>
<td>2,36</td>
<td>29,3</td>
<td>44,3</td>
</tr>
<tr class="odd">
<td></td>
<td>mayo</td>
<td>hembra</td>
<td>2422</td>
<td>35,3</td>
<td>1,91</td>
<td>29,4</td>
<td>43,7</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1402</td>
<td>37,3</td>
<td>2,31</td>
<td>29,5</td>
<td>45,8</td>
</tr>
<tr class="odd">
<td></td>
<td>junio</td>
<td>hembra</td>
<td>2516</td>
<td>34,6</td>
<td>2,19,28,2</td>
<td>43,2</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1234</td>
<td>36,7</td>
<td>2,92</td>
<td>29,5</td>
<td>46,2</td>
</tr>
<tr class="odd">
<td></td>
<td>julio</td>
<td>hembra</td>
<td>3725</td>
<td>36,9</td>
<td>2,19</td>
<td>30,4</td>
<td>44,5</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1720</td>
<td>38,5</td>
<td>2,80</td>
<td>28,8</td>
<td>46,5</td>
</tr>
<tr class="odd">
<td></td>
<td>agosto</td>
<td>hembra</td>
<td>4006</td>
<td>37,3</td>
<td>2,53</td>
<td>24,0</td>
<td>43,6</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1193</td>
<td>36,4</td>
<td>4,46</td>
<td>23,7</td>
<td>48,7</td>
</tr>
<tr class="odd">
<td><strong>L.amarillo</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>85</td>
<td>33,3</td>
<td>2,61</td>
<td>29,3</td>
<td>40,3</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>165</td>
<td>39,7</td>
<td>2,82</td>
<td>30,5</td>
<td>46,7</td>
</tr>
<tr class="odd">
<td></td>
<td>abril</td>
<td>hembra</td>
<td>297</td>
<td>31,4</td>
<td>2,58</td>
<td>19,6</td>
<td>44,6</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>1043</td>
<td>37,4</td>
<td>4,38</td>
<td>17,7</td>
<td>51,9</td>
</tr>
<tr class="odd">
<td></td>
<td>mayo</td>
<td>hembra</td>
<td>282</td>
<td>35,4</td>
<td>2,84</td>
<td>25,6</td>
<td>43,5</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>682</td>
<td>40,2</td>
<td>4,43</td>
<td>25,2</td>
<td>50,8</td>
</tr>
<tr class="odd">
<td></td>
<td>junio</td>
<td>hembra</td>
<td>5</td>
<td>33,1</td>
<td>2,62</td>
<td>31,3</td>
<td>36,3</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>190</td>
<td>37,9</td>
<td>3,91</td>
<td>27,4</td>
<td>49,4</td>
</tr>
<tr class="odd">
<td></td>
<td>julio</td>
<td>hembra</td>
<td>756</td>
<td>34,4</td>
<td>2,21</td>
<td>29,3</td>
<td>42,5</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>575</td>
<td>41,1</td>
<td>2,95</td>
<td>30,4</td>
<td>48,6</td>
</tr>
<tr class="odd">
<td><strong>Camarón</strong></td>
<td>marzo</td>
<td>hembra</td>
<td>164</td>
<td>29,7</td>
<td>2,33</td>
<td>24,8</td>
<td>35,6</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>86</td>
<td>29,4</td>
<td>1,39</td>
<td>26,5</td>
<td>32,6</td>
</tr>
<tr class="odd">
<td></td>
<td>junio</td>
<td>hembra</td>
<td>206</td>
<td>27,3</td>
<td>2,15</td>
<td>23,0</td>
<td>34,9</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>44</td>
<td>25,4</td>
<td>2,13</td>
<td>22,5</td>
<td>34,0</td>
</tr>
<tr class="odd">
<td></td>
<td>agosto</td>
<td>hembra</td>
<td>811</td>
<td>27,5</td>
<td>3,58</td>
<td>16,6</td>
<td>36,4</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>macho</td>
<td>189</td>
<td>24,3</td>
<td>4,11</td>
<td>15,4</td>
<td>39,0</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/proporcion_sexual_agosto.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Proporción sexual de langostino colorado (A) y langostino amarillo (B) durante agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/tallas_agosto.jpg" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Talla promedio (LC, mm) de langostino colorado y langostino amarillo por sexo, en el periodo enero 2016 a agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="aspectos-reproductivos" class="level2">
<h2 class="anchored" data-anchor-id="aspectos-reproductivos">3.2 Aspectos reproductivos</h2>
<p>Durante agosto de 2025, el 77 % de las hembras de langostino colorado se encontraron en estado ovígero, una proporción similar a la observada en el mismo período del año anterior (Fig. 8, Tabla 3)</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/madurez_agosto.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Hembras ovígeras de langostino colorado y langostino amarillo durante el año 2025, en comparacion con la media registrada entre los años 2017 a 2023 (línea verde)</figcaption>
</figure>
</div>
</div>
</div>
<section id="tabla-3.-porcentaje-de-hembras-ovígeras-y-hembras-maduras-de-langostino-colorado-y-amarillo-ups-2025." class="level5">
<h5 class="anchored" data-anchor-id="tabla-3.-porcentaje-de-hembras-ovígeras-y-hembras-maduras-de-langostino-colorado-y-amarillo-ups-2025."><em>Tabla 3. Porcentaje de hembras ovígeras y hembras maduras de langostino colorado y amarillo UPS 2025.</em></h5>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Recurso</strong></th>
<th><strong>Estado</strong></th>
<th><strong>mar.</strong></th>
<th><strong>abr.</strong></th>
<th><strong>may.</strong></th>
<th><strong>jun.</strong></th>
<th><strong>jul.</strong></th>
<th><strong>ago.</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L.colorado</strong></td>
<td>Normal</td>
<td>83%</td>
<td>21%</td>
<td>7%</td>
<td>8%</td>
<td>3%</td>
<td>7%</td>
</tr>
<tr class="even">
<td></td>
<td>Ovígeras</td>
<td>16%</td>
<td>76%</td>
<td>90%</td>
<td>85%</td>
<td>93%</td>
<td>78%</td>
</tr>
<tr class="odd">
<td></td>
<td>Madura</td>
<td>1%</td>
<td>3%</td>
<td>3%</td>
<td>7%</td>
<td>4%</td>
<td>15%</td>
</tr>
<tr class="even">
<td>Total n°</td>
<td></td>
<td>1590</td>
<td>2037</td>
<td>2422</td>
<td>2566</td>
<td>3725</td>
<td>4006</td>
</tr>
<tr class="odd">
<td><strong>L.amarillo</strong></td>
<td>Normal</td>
<td>100%</td>
<td>98%</td>
<td>7%</td>
<td>60%</td>
<td>2%</td>
<td>-</td>
</tr>
<tr class="even">
<td></td>
<td>Ovígeras</td>
<td>0%</td>
<td>2%</td>
<td>12%</td>
<td>40%</td>
<td>88%</td>
<td>-</td>
</tr>
<tr class="odd">
<td></td>
<td>Madura</td>
<td>0%</td>
<td>0%</td>
<td>1%</td>
<td>0%</td>
<td>10%</td>
<td>-</td>
</tr>
<tr class="even">
<td>Total n°</td>
<td></td>
<td>85</td>
<td>297</td>
<td>282</td>
<td>5</td>
<td>765</td>
<td>-</td>
</tr>
</tbody>
</table>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="composición-de-tallas" class="level2">
<h2 class="anchored" data-anchor-id="composición-de-tallas">3.3. Composición de tallas</h2>
<p>El análisis de tallas del langostino colorado no mostró diferencias significativas entre sexos (prueba t de Student, p &gt; 0,05). En el langostino colorado, los machos alcanzaron una talla media de 36,4 mm LC, y las hembras, que fue de 37,3 mm LC (Fig. 9). En cambio, en el camarón nailon las hembras registraron las mayores tallas promedio, superando a los machos (Tabla 2, Fig. 10).</p>
<p>En cuanto a la composición de tallas por zona de pesca, el langostino colorado presentó las tallas modales más pequeñas en Carranza, mientras que las tallas más grandes se registraron en las zonas Quintero y Pichilemu (Fig. 11). Para camarón nailon Chanco destacó con las mayores tallas y Punta Gallo con las menores en torno a 23 mm LC en machos y a 26 mm LC en hembras (Fig. 12).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/frec_colorado_sexo_agosto.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de langostino colorado entre sexos, en agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/frec_camaron_sexo_agosto.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de camarón nailon entre sexos, en agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/frec_colorado_tallas_agosto.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de langostino colorado en la UPS por zonas de pesca en agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/frec_camaron_tallas_agosto.jpg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Composición de tallas de camarón nailon en la UPS por zonas de pesca en agosto de 2025</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="fauna-acompañante" class="level2">
<h2 class="anchored" data-anchor-id="fauna-acompañante">3.4 Fauna acompañante</h2>
<p>Las operaciones de pesca realizadas durante agosto de 2025 por la flota de Crustaceos Pesca Sur evidenciaron la presencia de pejerrata, como fauna acompañante, en los caladeros de Punta Gallo, Algarrobo, Pichilemu, Iloca y Chanco (Fig. 13). Esta especie representó solo el 0.50 % del total de las capturas alcanzando un volumen de 3 toneladas.</p>
<p>En cuanto a la ocurrencia de otros recursos como fauna acompañante destaca la alta presencia de merluza y lenguado en la totalidad de caladeros visitados con valores entre los 50 y 200 kg/ha (Fig. 14). Tambien hay presencia de otros recursos como la Jaiba Paco y Jaiba Limón pero en menor cantidad (en termino de unidades por hora de arrastre) como se muestra en la Figura 14.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/pejerrata_agosto.jpeg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de los lances de pesca con captura de pejerrata en las capturas de camarón nailon, langostino colorado y langostino amarillo, y la fracción de pejerrata en las capturas totales, de junio año 2025</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_agosto_2025/fauna_Acomp_agosto.jpeg" class="img-fluid figure-img" style="width:110.0%"></p>
<figcaption>Distribución espacial y abundancia de la fauna acompañante en los lances de pesca orientados a langostinos colorado y langostinos amarillos por la flota arrastrera de Camanchaca Pesca Sur, junio de 2025</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>